WIZ-3900 sorting discussion by last message
wizaplace/discuss pull request #1
Opened 2019-11-18 13:04 UTC by halil-sak

* adding property messages in discussion entity
    * edit query in getAll method

2019-11-18 13:30 UTC, Nicolas-Masson-Wizaplace requested changes

2019-11-18 13:30 UTC, Nicolas-Masson-Wizaplace commented on src/Repository/DiscussionRepository.php
> +
Peut-être écrire une autre méthode du genre `getAllOrderedByMessageSendDate` et conserver `getAll` tel quel ?

2019-11-18 14:21 UTC, jeremy-wizaplace requested changes

2019-11-18 14:21 UTC, jeremy-wizaplace commented on src/Repository/DiscussionRepository.php
> +     * @return Paginator
```suggestion
     *
     * @return Paginator
```

2019-11-18 14:21 UTC, jeremy-wizaplace commented on src/Repository/DiscussionRepository.php
> +        return new Paginator($qb);
```suggestion

        return new Paginator($qb);
```

2019-11-18 14:24 UTC, cyprille requested changes

2019-11-18 14:24 UTC, cyprille commented on src/Repository/DiscussionRepository.php
> +        return new Paginator($qb);
```suggestion

        return new Paginator($qb);
```

2019-11-18 14:24 UTC, cyprille commented on src/Repository/DiscussionRepository.php
> +     * @return Paginator
```suggestion

     * @return Paginator
```

2019-11-18 14:24 UTC, cyprille commented on src/Repository/DiscussionRepository.php
> +        $qb->select('Discussion')
```suggestion
        $qb
            ->select('Discussion')
```

2019-11-19 08:58 UTC, halil-sak commented
Ecriture des tests Atoum en cours

2019-11-19 10:43 UTC, cyprille requested changes
Il ne manque plus que les tests ;)

2019-11-20 07:55 UTC, jeremy-wizaplace approved these changes

2019-11-20 12:28 UTC, Nicolas-Masson-Wizaplace requested changes

2019-11-20 12:28 UTC, Nicolas-Masson-Wizaplace commented on tests/Discuss/Repository/DiscussionRepository.php
> +        foreach ($repos['discuss']->getAllOrderedByMessageSendDate() as $d) {
évites les abbr. il faut que le nom de la variable nous laisse comprendre ce qui lui est assigné.
```suggestion
        foreach ($repos['discuss']->getAllOrderedByMessageSendDate() as $discussion) {
```

2019-11-20 12:28 UTC, Nicolas-Masson-Wizaplace commented on tests/Discuss/Repository/DiscussionRepository.php
> +        $message4 = $this->generateDiscussionAndMessage($repos, '10-12-2019', 4441, 4442, Status::DISPLAYED, Status::HIDDEN);
Tu peux peut être utiliser un array pour cette liste non ?

2019-11-20 13:47 UTC, cyprille requested changes

2019-11-20 13:47 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        $iniStatus
Globalement ici il manque le typage des propriétés et il faut aussi ne pas utiliser d'abréviations

2019-11-20 13:47 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +     * @param array  $repos
S'il s'agit d'un array, il faut préciser le type de son contenu ;)

2019-11-20 13:47 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        $repos['message']->save($message);
```suggestion
        $repos['message']->save($message);

```

2019-11-20 13:47 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +    public function test_getAllOrderedByMessageSendDate_()
Le nom de méthodes doit être en camelCase et non pas un mélange de snake_case / camelCase ;)

2019-11-20 13:47 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        ];
Je pense qu'il faut refactorer ce test qui est très long et fait à priori tout le temps le même traitement ;)

2019-11-20 16:09 UTC, halil-sak commented on tests/Discuss/Repository/DiscussionRepository.php
> +        $repos['message']->save($message);
La methode save de MessageRepo. ne fais pas que save elle modifie quelque champs du coup j'ai pas trop le choix à part si je me trompe

2019-11-21 14:58 UTC, cyprille requested changes
C'est mieux ^^
Je t'ai fait des retours pour le Code Style histoire que tu prennes le pli des bonnes pratiques PSR-12 : https://www.php-fig.org/psr/psr-12/ ;)

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +    public function generateMessageAndDiscussion(int $userId = null, Status $status = null)
Il manque le return type ;)

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        for($i=1; $i <= 3; $i++) {
```suggestion
        for ($i=1; $i <= 3; $i++) {
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +            foreach ([Status::DISPLAYED, Status::HIDDEN] as $initiator_hidden) {
```suggestion

            foreach ([Status::DISPLAYED, Status::HIDDEN] as $initiator_hidden) {
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +            foreach ([Status::DISPLAYED, Status::HIDDEN] as $initiator_hidden) {
Attention de bien utiliser du camelCase pour `initiator_hidden`

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                foreach ([Status::DISPLAYED, Status::HIDDEN] as $recipient_hidden) {
Attention de bien utiliser du camelCase pour `recipient_hidden`

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                        ->setUserStatus($recipientId, new Status($recipient_hidden))
Pourquoi tu set deux fois la même propriété ici ?

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                    if($userId !== null && $status !== null) {
```suggestion
                    if ($userId !== null && $status !== null) {
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                        if(
```suggestion
                        if (
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                                ($userId === $initiatorId && $initiator_hidden !== Status::HIDDEN) ||
Il faut passer le `||` à la ligne suivante ;)

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                            ) &&
Il faut passe le `&&` à la ligne suivante ;)

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                    else if($userId !== null) {
Attention au code style. Nous respectons les normes Symfony et PSR-12 : 

Les else s'écrivent comme ceci : https://www.php-fig.org/psr/psr-12/

```php
} else if($userId !== null) {
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                        if($userId === $initiatorId || $userId === $recipientId) {
```suggestion
                        if ($userId === $initiatorId || $userId === $recipientId) {
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                    else if ($status !== null) {
Même remarque pour le else que juste au dessus ;)

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                        if($initiator_hidden === $status->getValue() || $recipient_hidden === $status->getValue()) {
```suggestion
                        if ($initiator_hidden === $status->getValue() || $recipient_hidden === $status->getValue()) {
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                    else {
Même remarque

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        for($i=0;$i<10;++$i) {
```suggestion
        for ($i = 0; $i < 10; ++$i) {
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        //Retrieve All
```suggestion

        // Retrieve all
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        //Retrieve complete page
```suggestion
        // Retrieve complete page
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        //Retrieve incomplete page
```suggestion
        // Retrieve incomplete page
```

2019-11-21 14:58 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +        //Retrieve empty page
```suggestion
        // Retrieve empty page
```

2019-11-22 08:34 UTC, halil-sak commented on tests/Discuss/Repository/DiscussionRepository.php
> +                        ->setUserStatus($recipientId, new Status($recipient_hidden))
Une pour $initiatorId et l'autre pour $recipientId

2019-11-22 10:25 UTC, cyprille requested changes

2019-11-22 10:25 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                                ($userId === $recipientId && $recipientHidden !== Status::HIDDEN)
À mettre sur la ligne du dessus comme ça : 

```php
|| ($userId === $recipientId && $recipientHidden !== Status::HIDDEN)
```

2019-11-22 10:25 UTC, cyprille commented on tests/Discuss/Repository/DiscussionRepository.php
> +                            ($initiatorHidden === $status->getValue() || $recipientHidden === $status->getValue())
À mettre sur la ligne du dessus comme ça : 

```php
&& ($initiatorHidden === $status->getValue() || $recipientHidden === $status->getValue())
```

2019-11-22 11:01 UTC, cyprille approved these changes

2019-11-25 13:27 UTC, Nicolas-Masson-Wizaplace approved these changes

2019-11-26 08:48 UTC, merged